name: 'Local Github Cache with Docker'
description: 'Local Github Cache with Docker'
inputs:
  name:
    description: "Local cache name"
    required: true
  key_path:
    description: "Local cache key path"
    required: true
runs:
  using: "composite"
  steps:
    - name: ${{ inputs.name.capitalize }} Build Cache for Docker
      uses: actions/cache@v4
      id: cache
      with:
        path: |
          ${{ inputs.name }}-lib-cache
          ${{ inputs.name }}-build-cache
        key: ${{ runner.os }}-${{ inputs.name }}-cache-${{ hashFiles(inputs.key_path) }}

    - name: inject ${{ inputs.name }}-build-cache into docker
      uses: reproducible-containers/buildkit-cache-dance@v3
      with:
        cache-map: |
          {
            "${{ inputs.name }}-lib-cache": "/root/.cache/${{ inputs.name }}-lib",
            "${{ inputs.name }}-build-cache": "/root/.cache/${{ inputs.name }}-build"
          }
        skip-extraction: ${{ steps.cache.outputs.cache-hit }}
